apiVersion: v1
kind: ConfigMap

metadata:
  name: url-shortener-config
  namespace: url-shortener

data:
  POSTGRES_DB: url_shortener
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"

  DATABASE_URL: postgresql://postgres:postgres@postgres-service:5432/url_shortener